ci: await GitHub Pages build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,10 +3,14 @@ version: 2.1
 jobs:
   build_and_publish:
     docker:
-      - image: cibuilds/hugo:0.54.0
+      - image: alpine
     working_directory: ~/project
     shell: /usr/bin/env bash -euo pipefail
     steps:
+      - run:
+          name: Install Dependencies
+          shell: /bin/sh # Until this is run, we don't have bash.
+          command: apk add bash make git openssh curl hugo jq
       - add_ssh_keys:
           fingerprints:
             - "00:b6:0c:6b:77:f4:08:7e:06:0f:81:b2:43:09:2b:11"
@@ -29,6 +33,25 @@ jobs:
       - run:
           name: Publish
           command: make publish
+      - run:
+          name: Await GitHub Pages Build
+          command: |
+            URL="https://api.github.com/repos/fieldnotes-tech/fieldnotes-tech.github.io/pages/builds?per_page=3"
+            STATUS=nothing
+            COUNT=0
+            SHA=$(cd public && git rev-parse HEAD)
+            until [ $STATUS = built ] || [ $STATUS = errored ] || [ $COUNT = 60 ]; do
+              sleep 1
+              COUNT=$((COUNT+1))
+              STATUS=$(curl -sfu $GITHUB_USER:$GITHUB_API_TOKEN $URL \
+              | jq -r ".[] | select(.commit == env.CIRCLE_SHA1)" | .status)
+              [ -n "$STATUS" ] || STATUS=nothing
+            done
+            if [ $STATUS != built ]; then
+              echo "Failed: final status from github was '$STATUS'"
+              exit 1
+            fi
+            echo "GitHub Pages build complete."
 
 workflows:
   publish:
